#!/usr/bin/env python3
from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
LIB = ROOT / "lib"
if str(LIB) not in sys.path:
    sys.path.insert(0, str(LIB))

from agents.definitions import ensure_definitions_loaded, get_definition
from agents.jobs.broker import AgentJobBroker
from agents.jobs.store import AgentJobStore
from agents.security.actions import ActionRequest
from agents.security.broker import CapabilityBroker
from skills.test_case.dedupe import partition_new_cases
from skills.test_case.generator import generate_test_cases
from skills.test_case.models import StoryContext, TestCase
from skills.test_case.skill import generate_test_cases_for_issue


class FakeBitable:
    def __init__(self) -> None:
        self.tables = [{"table_id": "tbl1", "name": "Test Cases"}]
        self.fields = [{"field_name": name} for name, _ in (
            ("Story Key", 1),
            ("Story Title", 1),
            ("Title", 1),
            ("Steps", 1),
            ("Expected Result", 1),
            ("Type", 1),
            ("Status", 1),
            ("Source Hash", 1),
            ("Generated At", 1),
            ("Generated By", 1),
        )]
        self.views: list[dict[str, Any]] = []
        self.records: list[dict[str, Any]] = []

    def list_tables(self, app_token: str) -> list[dict[str, Any]]:
        return self.tables

    def create_table(self, app_token: str, name: str) -> dict[str, Any]:
        table = {"table_id": "tbl_new", "name": name}
        self.tables.append(table)
        return table

    def list_fields(self, app_token: str, table_id: str) -> list[dict[str, Any]]:
        return self.fields

    def create_field(self, app_token: str, table_id: str, *, name: str, field_type: int = 1) -> dict[str, Any]:
        field = {"field_name": name, "type": field_type}
        self.fields.append(field)
        return field

    def list_views(self, app_token: str, table_id: str) -> list[dict[str, Any]]:
        return self.views

    def create_view(self, app_token: str, table_id: str, *, name: str, view_type: str = "grid") -> dict[str, Any]:
        view = {"view_name": name, "view_type": view_type}
        self.views.append(view)
        return view

    def list_records(self, app_token: str, table_id: str, *, page_size: int = 100) -> list[dict[str, Any]]:
        return list(self.records)

    def create_record(self, app_token: str, table_id: str, fields: dict[str, Any]) -> dict[str, Any]:
        record = {"record_id": f"rec{len(self.records)+1}", "fields": dict(fields)}
        self.records.append(record)
        return record


class FakeSheets:
    def __init__(self) -> None:
        self.rows: list[list[Any]] = []
        self.appended: list[list[Any]] = []

    def resolve_sheet(self, spreadsheet_token: str, sheet_name: str = "Sheet1") -> dict[str, Any]:
        return {"sheetId": "sht1", "title": sheet_name}

    def get_values(self, spreadsheet_token: str, range_a1: str) -> list[list[Any]]:
        return list(self.rows)

    def append_values(self, spreadsheet_token: str, *, sheet_id: str, values: list[list[Any]], start_col: str = "A", end_col: str = "J") -> dict[str, Any]:
        for row in values:
            self.rows.append(list(row))
            self.appended.append(list(row))
        return {"updatedRows": len(values)}


class TestCaseSkillTests(unittest.TestCase):
    def test_generator_covers_ac_types(self) -> None:
        story = StoryContext(
            key="MBPAS-1601",
            type="Story",
            summary="Login flow",
            description="desc",
            acceptance_criteria=["User can log in with email", "Invalid password is rejected"],
        )
        cases = generate_test_cases(story)
        types = {c.case_type for c in cases}
        self.assertEqual(types, {"Functional", "Negative", "Boundary"})
        self.assertGreaterEqual(len(cases), 6)
        for case in cases:
            self.assertTrue(case.title)
            self.assertTrue(case.steps)
            self.assertTrue(case.expected_result)
        zh = generate_test_cases(story, language="zh-Hant")
        self.assertTrue(any("正常路徑" in c.title for c in zh))

    def test_dedupe_skips_existing_titles(self) -> None:
        generated = [
            TestCase("A", "1", "ok", "Functional", "MBPAS-1", "t"),
            TestCase("B", "1", "ok", "Functional", "MBPAS-1", "t"),
            TestCase("a", "1", "ok", "Functional", "MBPAS-1", "t"),
        ]
        created, skipped = partition_new_cases(generated, {"A"})
        self.assertEqual([c.title for c in created], ["B"])
        self.assertEqual(len(skipped), 2)

    def test_skill_writes_additive_rows(self) -> None:
        fake = FakeBitable()
        fake.records.append({"fields": {"Story Key": "MBPAS-1601", "Title": "MBPAS-1601 AC1 正常路徑：User can log in"}})

        def reader(key: str) -> StoryContext:
            return StoryContext(
                key=key,
                type="Story",
                summary="Login flow",
                description="",
                acceptance_criteria=["User can log in"],
            )

        result = generate_test_cases_for_issue(
            project="mbpass",
            issue_key="MBPAS-1601",
            config={"projects": {"mbpass": {"test_case": {"base_app_token": "bas_test", "table_name": "Test Cases", "language": "zh-Hant"}}}},
            client=fake,
            story_reader=reader,
        )
        self.assertEqual(result["status"], "completed")
        self.assertGreaterEqual(result["created"], 2)
        self.assertGreaterEqual(result["skipped_existing"], 1)
        self.assertIn("MBPAS-1601", result["view_name"])
        self.assertTrue(result["summary"])

    def test_skill_writes_spreadsheet_rows(self) -> None:
        fake = FakeSheets()

        def reader(key: str) -> StoryContext:
            return StoryContext(
                key=key,
                type="Story",
                summary="Login flow",
                description="",
                acceptance_criteria=["User can log in"],
            )

        result = generate_test_cases_for_issue(
            project="mbpass",
            issue_key="MBPAS-1601",
            config={
                "projects": {
                    "mbpass": {
                        "test_case": {
                            "destination": "sheet",
                            "spreadsheet_token": "OG4Js7cIlh7d0QtHOEnc1kDfnvf",
                            "sheet_name": "Sheet1",
                            "language": "zh-Hant",
                        }
                    }
                }
            },
            sheets_client=fake,
            story_reader=reader,
        )
        self.assertEqual(result["status"], "completed")
        self.assertGreaterEqual(result["created"], 3)
        self.assertTrue(any(row and row[0] == "Story Key" for row in fake.rows))
        self.assertIn("/sheets/OG4Js7cIlh7d0QtHOEnc1kDfnvf", result["sheet_url"])

    def test_broker_mark_action_allowed(self) -> None:
        ensure_definitions_loaded()
        mark = get_definition("mark")
        assert mark is not None
        self.assertIn("test_case.generate", mark.capabilities.actions)
        fake = FakeBitable()

        def reader(key: str) -> StoryContext:
            return StoryContext(key=key, type="Bug", summary="Fix", description="", acceptance_criteria=["bug fixed"])

        from unittest import mock

        with mock.patch("skills.test_case.skill.generate_test_cases_for_issue") as gen:
            gen.return_value = {"status": "completed", "summary": "ok", "created": 1, "generated": 1}
            receipt = CapabilityBroker(
                config={"access": {"mutation_allowed_user_ids": ["ou_owner"]}}
            ).execute(
                ActionRequest(
                    agent_id="mark",
                    action="test_case.generate",
                    project_slug="mbpass",
                    actor_user_id="ou_owner",
                    chat_id="oc1",
                    thread_id="",
                    source_message_id="om1",
                    trace_id="tr1",
                    resource={"issue_key": "MBPAS-1601"},
                    arguments={"issue_key": "MBPAS-1601"},
                    explicit_authorization=True,
                )
            )
            self.assertEqual(receipt.status, "succeeded")


class MilchickJobTests(unittest.TestCase):
    def test_milchick_definition_registered(self) -> None:
        ensure_definitions_loaded()
        milchick = get_definition("milchick")
        assert milchick is not None
        self.assertEqual(milchick.role, "orchestrator")
        self.assertIn("agent.job.create", milchick.capabilities.actions)
        self.assertNotIn("test_case.generate", milchick.capabilities.actions)

    def test_job_dependency_and_summary(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            store = AgentJobStore(Path(tmp) / "jobs.sqlite3")
            broker = AgentJobBroker(store)
            parent = broker.create_parent(
                project="mbpass",
                requested_by="ou_owner",
                delegated_by="milchick",
                source_message_id="om1",
                chat_id="oc1",
                thread_id="th1",
                trace_id="tr1",
            )
            first = broker.create_child(
                parent=parent,
                target_agent="irving",
                capability="risk.resolve",
                input_data={"finding_id": "FIND-1"},
            )
            second = broker.create_child(
                parent=parent,
                target_agent="mark",
                capability="test_case.generate",
                input_data={"issue_key": "MBPAS-1601"},
                depends_on=[first.job_id],
            )
            self.assertEqual(first.status, "ready")
            self.assertEqual(second.status, "queued")
            first.status = "completed"
            store.save(first)
            broker.refresh_dependencies(parent.job_id)
            second = store.get(second.job_id)
            assert second is not None
            self.assertEqual(second.status, "ready")
            summary = broker.summarize(parent.job_id)
            self.assertIn(summary["overall_state"], {"running", "completed", "blocked"})


if __name__ == "__main__":
    unittest.main()
