from __future__ import annotations

import os
from typing import Any, Optional

from feishu.config import load_agents_config, read_lumen_env_var


REQUIRED_FIELDS = (
    ("Story Key", 1),
    ("Story Title", 1),
    ("Title", 1),
    ("Steps", 1),
    ("Expected Result", 1),
    ("Type", 1),
    ("Status", 1),
    ("Source Hash", 1),
    ("Generated At", 1),
    ("Generated By", 1),
)

SUPPORTED_LANGUAGES = ("zh-Hant", "zh-Hans", "en")


def normalize_test_case_language(value: str) -> str:
    raw = str(value or "").strip().lower().replace("_", "-")
    if raw in {"zh-hant", "zh-tw", "zh-hk", "zh-mo", "zh", "zh-cht", "traditional", "zh-traditional"}:
        return "zh-Hant"
    if raw in {"zh-hans", "zh-cn", "zh-sg", "simplified"}:
        return "zh-Hans"
    if raw in {"en", "english"}:
        return "en"
    return "zh-Hant"


def load_test_case_config(
    project: str,
    *,
    config: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    data = config if isinstance(config, dict) else load_agents_config()
    slug = str(project or "").strip().lower()
    projects = data.get("projects") if isinstance(data.get("projects"), dict) else {}
    project_cfg = projects.get(slug) if isinstance(projects.get(slug), dict) else {}
    test_case = project_cfg.get("test_case") if isinstance(project_cfg.get("test_case"), dict) else {}
    if not test_case:
        mark = data.get("mark") if isinstance(data.get("mark"), dict) else {}
        mark_tc = mark.get("test_case") if isinstance(mark.get("test_case"), dict) else {}
        nested = mark_tc.get("projects") if isinstance(mark_tc.get("projects"), dict) else {}
        test_case = nested.get(slug) if isinstance(nested.get(slug), dict) else {}
    app_token = str(test_case.get("base_app_token") or "").strip()
    token_env = str(test_case.get("base_app_token_env") or "").strip()
    if not app_token and token_env:
        app_token = os.environ.get(token_env, "").strip() or read_lumen_env_var(token_env).strip()
    table_name = str(test_case.get("table_name") or "Test Cases").strip() or "Test Cases"
    language = normalize_test_case_language(str(test_case.get("language") or "zh-Hant"))
    base_host = str(test_case.get("feishu_base_host") or "inspiregroup.feishu.cn").strip() or "inspiregroup.feishu.cn"
    return {
        "project": slug,
        "base_app_token": app_token,
        "table_name": table_name,
        "view_strategy": str(test_case.get("view_strategy") or "story"),
        "language": language,
        "feishu_base_host": base_host,
        "raw": test_case,
    }
