from __future__ import annotations

import hashlib
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any


CASE_TYPES = ("Functional", "Negative", "Boundary")


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def normalize_title(title: str) -> str:
    text = re.sub(r"\s+", " ", str(title or "").strip().lower())
    return text


def source_hash(*, story_key: str, title: str, steps: str, expected: str) -> str:
    payload = f"{story_key}|{normalize_title(title)}|{steps}|{expected}"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


@dataclass
class StoryContext:
    key: str
    type: str
    summary: str
    description: str
    acceptance_criteria: list[str] = field(default_factory=list)
    comments: list[dict[str, Any]] = field(default_factory=list)
    attachments: list[dict[str, Any]] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class TestCase:
    title: str
    steps: str
    expected_result: str
    case_type: str
    story_key: str
    story_title: str
    status: str = "Active"
    source_hash: str = ""
    generated_at: str = ""
    generated_by: str = "mark"

    def ensure_meta(self) -> None:
        if not self.generated_at:
            self.generated_at = utc_now()
        if not self.source_hash:
            self.source_hash = source_hash(
                story_key=self.story_key,
                title=self.title,
                steps=self.steps,
                expected=self.expected_result,
            )

    def to_fields(self) -> dict[str, Any]:
        self.ensure_meta()
        return {
            "Story Key": self.story_key,
            "Story Title": self.story_title,
            "Title": self.title,
            "Steps": self.steps,
            "Expected Result": self.expected_result,
            "Type": self.case_type,
            "Status": self.status,
            "Source Hash": self.source_hash,
            "Generated At": self.generated_at,
            "Generated By": self.generated_by,
        }

    def to_sheet_fields(self) -> dict[str, Any]:
        self.ensure_meta()
        return {
            "Title": self.title,
            "Steps": self.steps,
            "Expected Result": self.expected_result,
            "Type": self.case_type,
            "Verify Status": "",
            "Note": "",
        }
